language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=tensor_lda
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      NUMPY_VERSION="1.19.5" SCIPY_VERSION="1.16.0" CYTHON_VERSION="0.29.21"

install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
